#searches a given link for artists that you specify in the names list.

import requests

try:
    def search():
        # user will input a URL for a convention's guests page or artist page or wherever they have their 
        # attendees listed.
        Site = input(
            [r'Please enter the site you would like to search i.e. https://iccollectorsconvention.com/artists/'])
        # This is where you list which guests you are looking for.
        names = ['MARK MCCREERY', 'AARON MCBRIDE', 'ADAM HUGHES', 'ADAM PORT', 'ADAM SCHICKLING', 'ADAM WARREN',
                 'AL WILLIAMSON', 'ALEC GUINESS', 'ALEX GARNER', 'ALEX INIGUEZ', 'ALEX PARDEE', 'ALLEN NUNIS',
                 'ALLISON SOHN', 'AMANDA CONNER', 'AMY BETH CHRISTENSON', 'AMY PRONOVOST', 'ANDREW FRY',
                 'ANDREW SKILLETER', 'ANGELINA BENEDETTI', 'ANGELO TORRES', 'ANIL SHARMA', 'ARTHUR ADAMS',
                 'ARTHUR SUYDAM', 'ASHLEY WOOD', 'BASIL GOGOS', 'BATTLE AT THE SARLACC PIT GAME', 'BEN ABUSAADA',
                 'BENJAMIN CARRE', 'BILL SCHMIDT', 'BILL SIENKIEWICZ', 'BO HAMPTON', 'BOB FINGERMAN', 'BOB LAYTON',
                 'BOB STEVLIC', 'BORIS VALLEJO', 'BRAD ANDERSON', 'BRAD ANDERSON/JAN DUURSEMA', 'BRAD HUDSON',
                 'BRANDON PETERSON', 'BRET BLEVINS', 'BRIAN ASHMORE', 'BRIAN CHING', 'BRIAN HORTON', 'BRIAN KONG',
                 'BRIAN ROOD', 'BRIAN STELFREEZE', 'BRUCE TIMM', 'BRUCE ZICK', 'BRYAN SNUFFER', 'BUNNY CARTER',
                 'C. SCOTT MORSE', 'CALEB KING', 'CAM KENNEDY', 'CARLOS CABALEIRO', 'CAT STAGGS', 'CATHLEEN THOLE',
                 'CATO YASUMURA BEHAEGHEL', 'CHARLES VESS', 'CHRIS CLARK', 'CHRIS HOPEWELL', 'CHRIS MEEKS',
                 'CHRIS SPROUSE', 'CHRIS TREVAS', 'CHRIS WAHL', 'CHRIS WHITE', 'CHRISTIAN WAGGONER',
                 'CHRISTOPHER MOELLER', 'CLARK MITCHELL', 'CLARK SCHAFFER', 'CLIFF CHANG', 'CLIFF CHIANG',
                 'CLIFF CRAMP', 'CLYDE CALDWELL', 'CLYDE CLADWELL', 'COLLEEN DORAN', 'COURTNEY SKINNER', 'CULLY HAMNER',
                 'CYNTHIA MARTIN', 'DALE KEOWN', 'DAN BARRY', 'DAN BERGREN', 'DAN COLON', 'DAN GOOZEE', 'DAN MASSO',
                 'DANIEL BRERETON', 'DANIEL BRERTON', 'DARRIN PEPE', 'DARWYN COOKE', 'DAVE COCKRUM', 'DAVE DORMAN',
                 'DAVE FILONI', 'DAVE GIBBONS', 'DAVE HOOVER', 'DAVE KINSEY', 'DAVE SEELEY', 'DAVE STEVENS',
                 'DAVID DEITRICK', 'DAVID GROVE', 'DAVID LAPHAM', 'DAVID LOWERY', 'DAVID MICHAEL BECK',
                 'DAVID O. MILLER', 'DAVID PETERSON', 'DAVID RABBITTE', 'DEL NICHOLS', 'DIANE DE GROAT',
                 'DIANE DEGROAT', 'DON PUNCHATZ', 'DONATO GIANCOLA', 'DOUG CHIANG', 'DOUG COWAN', 'DOUG WHEATLEY',
                 'DREW FRIEDMAN', 'DREW STRUZAN', 'EARL NOREM', 'ED BINKLEY', 'ED COX', 'ED REPKA', 'ELI MAFFEI',
                 'ERIC LEHTONEN', 'ERIK MAELL', 'ESTEBAN MAROTO', 'EVAN SHOMAN', 'FASTNERLARSON',
                 'FINE MOLDS MODEL KIT', 'FLORIAN BERTMER', 'FRANCHESCO', 'FRANK BRUNNER', 'FRANK KADAR',
                 'FRANK KELLY FREAS', 'FRANK MILLER', 'FRANK STOCKTON', 'GABOR SZIKSZAI', 'GAHAN WILSON', 'GARY BIALKE',
                 'GARY GIANNI', 'GARY PULLEN', 'GARY S. BIALKE', 'GENE COLAN', 'GENE LEMERY', 'GEOF DARROW',
                 'GEORGE EVANS', 'GEORGE GAADT', 'GEORGE PEREZ', 'GEORGE PRATT', 'GERRY DALY', 'GERRY GARCIA',
                 'GIL KANE', 'GRANT GOULD', 'GRANT SEARCEY', 'GREG AND TIM HILDEBRANDT', 'GREG CAPULLO',
                 'GREG HILDEBRANDT', 'GREG KNIGHT', 'GREG THEAKSTON', 'GREG WINTERS', 'HECTOR GOMEZ', 'HIGH FLEMING',
                 'HOANG NGUYEN', 'HOON', 'HOWARD CHAYKIN', 'HUGH FLEMING', 'IGOR KORDEY', 'INGRID HARDY', 'J H SMITH',
                 'J. SCOTT CAMPBELL', 'J. SCOTT CAMPBELL/ALEX GARNER', 'JACK DAVIS', 'JACK KIRBY', 'JAE LEE',
                 'JAMIE RICHARDS', 'JAN DUURSEMA', 'JANINE JOHNSTON', 'JASON EDMISTON', 'JASON KEITH',
                 'JASON KEITH/LUKE ROSS', 'JASON PALMER', 'JASON PEARSON', "JEAN 'MOEBIUS' GIRAUD", 'JEAN FRISANO',
                 'JEAN GIRAUD', 'JEFF CARLISLE', 'JEFF SOTO', 'JEFF WATTS', 'JEFFREY JONES', 'JENNIFER ALLYN',
                 'JERMAINE ROGERS', 'JEROME MOORE', 'JERRY VANDERSTELT', 'JESSICA HICKMAN', 'JH SMITH', 'JILL THOMPSON',
                 'JIM CAMPBELL', 'JIM MEHSLING', 'JIM REDDINGTON', 'JIM STARLIN', 'JIM STERANKO', 'JIM VALENTINO',
                 'JIMMY PALMIOTTI', 'JOANN DALEY', 'JOE CIARDIELLO', 'JOE CORONNEY', 'JOE CORRONEY', 'JOE DEVITO',
                 'JOE JOHNSON', 'JOE JUSKO', 'JOE PHILLIPS', 'JOE QUESADA', 'JOE SMITH', 'JOHN ALVIN',
                 'JOHN B. HIGGINS', 'JOHN BERKEY', 'JOHN BOLTON', 'JOHN BROSIO', 'JOHN BYRNE', 'JOHN CELESTRI',
                 'JOHN EAVES', 'JOHN GAMPERT', 'JOHN HIGGINS', 'JOHN K. SNYDER', 'JOHN K. SNYDER III', 'JOHN MOLLO',
                 'JOHN NADEAU', 'JOHN PAUL LEON', 'JOHN PAUL LONA', 'JOHN POUND', 'JOHN SNYDER', 'JOHN VAN FLEET',
                 'JON FOSTER', 'JON J MUTH', 'JP PEREZ', 'JUNE BRIGMAN', 'JUNE BRIGMAN/ROY RICHARDSON', 'JUSTIN CHIN',
                 'JUSTIN ERICKSON', 'KARL ALTSTATTER', 'KARL KESEL', 'KATIE COOK', 'KAZUHIKO SANO', 'KEITH CARTER',
                 'KEITH GIFFEN', 'KEITH TUCKER', 'KELLEY JONES', 'KEN BARR', 'KEN KELLY', 'KEN STEACY', 'KENT WILLIAMS',
                 'KEVIN B CLEVELAND', 'KEVIN B. CLEVELAND', 'KEVIN CLEVELAND', 'KEVIN GRAHAM', 'KEVIN NOWLAN',
                 "KEVIN O'NEILL", 'KEVING GRAHAM', 'KIA ASAMIYA', 'KILIAN PLUNKETT', 'KOIZUMI KAZUKI PRODUCTIONS',
                 'KRIS PENIX', 'KYLE BABBIT', 'KYLE BABBITT', 'KYLE BAKER', 'LAWRENCE REYNOLDS', 'LE BLANC',
                 'LEE KOHSE', 'LEINIL YU', 'LES DORSCHEID', 'LIBBY PERSZYK KATHMAN', 'LINDA MEDLEY', 'LIONEL TALARO',
                 'LOU HARRISON', 'LOUISE DRAPER', 'LUKE ROSS', 'LURENE HAINES', 'MARCIA DYE', 'MARK "CRASH" MCCREERY',
                 'MARK CHIARELLO', 'MARK HARRISON', 'MARK J. MANCINI', 'MARK MAHALEY', 'MARK MANCINI', 'MARK MANGUM',
                 'MARK MCHALEY', 'MARK NELSON', 'MARK PACELLA', 'MARK RAATS', 'MARK SCHULTZ', 'MARK ZUG', 'MARKUS',
                 'MARSHA PARKINS', 'MARSHALL ARISMAN', 'MARSHALL ROGERS', 'MARTIN "BUCKY" CAMERON', 'MARTIN ANSEN',
                 'MARTIN CAERON', 'MATHIEU LAFFRAY', 'MATT BUSCH', 'MATT GLEBE', 'MATT HALEY', 'MATT MALDONADO',
                 'MELANIE TAYLOR KENT', 'MICHAEL ALLRED', 'MICHAEL DAVID WARD', 'MICHAEL DURON', 'MICHAEL GOLDEN',
                 'MICHAEL MIGNOLA', 'MICHAEL WHELAN', 'MICHAEL WILLIAM KALUTA', 'MICK GLEBE', 'MIKE AVON OEMING',
                 'MIKE GRELL', 'MIKE JAMES HORGAN', 'MIKE KUNGL', 'MIKE LEMOS', 'MIKE MAYHEW', 'MIKE MCMAHON',
                 'MIKE SAPUTO', 'MIKE SMITHSON', 'MIKE ZECK', 'MIRAN KIM', 'MISHEL ROBINADEH', "MITCH O'CONNELL",
                 'MOEBIUS', 'MONTE M. MOORE', 'MORGAN WIESTLING', 'NATHAN HAMILL', 'NELSON', 'NELSON DE CASTRO',
                 'NICHOLE FALK', 'NICK CHOLES', 'NICOLE FALK', 'NILO RODIS-JAMERO', 'NORIYOSHI OHARI', 'NORM DWYER',
                 'OLLY MOSS', 'OTIS FRAMPTON', 'P. CAMPION', 'P. CRAIG RUSSELL', 'PAPUZZA', 'PAT PARIS',
                 'PATRICK SCHOENMAKER', 'PAUL ANDREWS', 'PAUL CAMPION', 'PAUL CHADWICK', 'PAUL GULACY', 'PAUL LEE',
                 'PAUL SHIPPER', 'PETER FERK', 'PHILLIPE DRUILLET', 'R. HARRIS', 'RALPH MCQUARRIE', 'RALPH REESE',
                 'RANDY GALLEGOS', 'RANDY MARTINEZ', 'RAY LAGO', 'REBECCA GUAY', 'RHYS COOPER', 'RICARDO DELGADO',
                 'RICH BUCKLER', 'RICH HEDDEN', 'RICH MOLINELLI', 'RICK BUCKLER', 'RICK GEARY', 'ROB DOBI',
                 'ROBERTO CAMPOS', 'ROBERTO CAMPUS', 'RON BROWN', 'RON COBB', 'RON LUSSIER', 'ROY RICHARDSON',
                 'RUSS WALKS', 'RUSSELL WALKS', 'RYAN HESHKA', 'SAM KIETH', 'SAN-JULIAN', 'SARAH WILKINSON',
                 'SCOTT GUSTAFSON', 'SCOTT HAMPTON', 'SCOTT NEELY', 'SEAN PHILLIPS', 'SERGIO ARAGONES', 'SHAN JIANG',
                 'SHAWN C. MARTINBROUGH', 'SIMON BISLEY', 'SOLLY MOHAMED', 'SONIA HILLIOS', 'STEPHANE ROUX',
                 'STEPHANIE ROSALES', 'STEVE CHORNEY', 'STEVE DITKO', 'STEVE FASTNER/JAY LARSON', 'STEVE MCNIVEN',
                 'STEVE THOMAS', 'STEVEN CHORNEY', 'STEVEN DAILY', 'STEVEN R. REISS', 'SYLVAIN', 'SYLVAIN (DESPRETZ)',
                 'TAYLOR STOUT', 'TED BOONTHANAKIT', 'TERESE NIELSEN', 'TERESE NIELSON', 'TERRY AUSTIN', 'THOM ANG',
                 'THOMAS BLACKSHEAR', 'THOMAS DEZUNGA', 'THOMAS DEZUNIGA', 'THOMAS WILLIAM YEATES II', 'TIM BRADSTREET',
                 'TIM BURGARD', 'TIM ELDRED', 'TIM PROCTOR', 'TIM SMITH', 'TIM TRUMAN', 'TODD AARON SMITH',
                 'TODD ANDREWS', 'TODD SLATER', 'TODD TREADWAY', 'TOM CANTRELL', 'TOM HODGES',
                 'TOM HODGES/PABLO HIDALGO', 'TOM JUNG', 'TOM TAGGART', 'TOM WHALEN', 'TOMER HANUKA',
                 'TOMMY LEE EDWARDS', 'TONY AUTH', 'TRENT WESTBROOK', 'TSUNEO SANDA', 'TSUYOSHI NAGANO', 'VINCE LOCKE',
                 'WALTER MCDANIEL', 'WALTER SIMONSON', 'WARREN FU', 'WHILCE PORTACIO', "WILLIAM O'NEIL",
                 'WILLIAM SCHMIDT', 'WILLIAM SELBY', 'WILLIAM SILVERS', 'WILLIAM STOUT', 'WOJTEK SIUDMAK',
                 'ZINA SAUNDERS', 'ZOHAR LAZAR', 'ZOLTAN BOROS', 'GABOR SZIKSZAI']
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) "
                          "Chrome/72.0.3626.119 Safari/537.36"}

        print('searching page for artists')
        counter = 0
        page = requests.get(Site, headers=headers)
        for y in names:
            if str(y) in page.text.upper():
                print(str(y))
                counter = counter + 1
        if counter <= 0:
            print('no matches')


    while True:
        search()
except Exception as e:
    print("type error: " + str(e))
    pass
